common: &defaults
  name: <%= "meowmates (#{Rails.env})" %>
  key: <%= ENV["SCOUT_KEY"] %>
  log_level: info
  monitor: true

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults
