# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  RACK_ENV: development REDISTOGO_URL=redis://localhost:6379/
  secret_key_base: 60d47b0c616136ad34cb09ad5c0b5fa3f4cf938128fad8b52664881886355a6525ba8384f2cd81f8c051abd9e276a88c6e0504685b2a6f4489d3d406d65bc3f6
  pet_key: 112c23a2acff1a86ceb51dac5c5f8985
  pet_secret: a9070ba4ee6751f15f9f14b7e52ec361


 # TODO Add Redis connection
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  KEEN_PROJECT_ID: <%= ENV["KEEN_PROJECT_ID"] %>
  KEEN_WRITE_KEY: <%= ENV["KEEN_WRITE_KEY"] %>
  pet_key: <%= ENV["PET_KEY"] %>
  pet_secret: <%= ENV["PET_SECRET"] %>
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  KEEN_PROJECT_ID: <%= ENV["KEEN_PROJECT_ID"] %>
  KEEN_WRITE_KEY: <%= ENV["KEEN_WRITE_KEY"] %>
  pet_key: <%= ENV["PET_KEY"] %>
  pet_secret: <%= ENV["PET_SECRET"] %>
