require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AdoptionAnimalsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Adoptionanimal. As you add validations to Adoptionanimal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {"species" => "cat",
    "name" => "rspec anamil",
    "pet_id" => 1,
    "gender" => "M",
    "fixed" => 1,
    "breed" => "cat",
    "found_on" => "1/1/2001",
    "scraped_at" => "1/1/2001",
    "shelter_id" => 1,
    "image_id" => 1 }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdoptionanimalsController. Be sure to keep this updated too.
  # let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all adoption_animals as @adoption_animals" do
      AdoptionAnimal = AdoptionAnimal.all
      get :index
      expect(assigns(:adoption_animals)).to eq(AdoptionAnimal)
    end
  end

  describe "GET #show" do
    it "assigns the requested adoption_animal as @adoption_animal" do
      get :show, params: { id: 12 }
      expect(:adoption_animal).to eq :adoption_animal
    end
  end

  describe "GET #new" do
    it "assigns a new adoption_animal to @adoption_animal" do
      get :new
      expect(assigns(:adoption_animal)).to be_a_new(AdoptionAnimal.AdoptionAnimal)
    end
  end

  describe "GET #edit" do
    it "assigns the requested adoption_animal as @adoptionanimal" do
      AdoptionAnimal = AdoptionAnimal.create! valid_attributes
      get :edit, params: {id: adoptionanimal.to_param}
      expect(assigns(:adoption_animal)).to eq(AdoptionAnimal)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AdoptionAnimal" do
        expect {
          post :create, params: {adoption_animal: valid_attributes}
        }.to change(AdoptionAnimal, :count).by(1)
      end

      it "assigns a newly created adoption_animal as @adoptionanimal" do
        post :create, params: {adoption_animal: valid_attributes}
        expect(assigns(:adoption_animal)).to be_a(AdoptionAnimal)
        expect(assigns(:adoption_animal)).to be_persisted
      end

      it "redirects to the created adoptionanimal" do
        post :create, params: {adoption_animal: valid_attributes}
        expect(response).to redirect_to(AdoptionAnimal.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved adoptionanimal as @adoptionanimal" do
        post :create, params: {adoption_animal: invalid_attributes}
        expect(assigns(:adoptionanimal)).to be_a_new(AdoptionAnimal)
      end

      it "re-renders the 'new' template" do
        post :create, params: {adoption_animal: invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested AdoptionAnimal" do
        adoptionanimal = AdoptionAnimal.create! valid_attributes
        put :update, params: {id: adoption_animal.to_param, adoptionanimal: new_attributes}
        adoptionanimal.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested adoptionanimal as @adoptionanimal" do
        adoptionanimal = AdoptionAnimal.create! valid_attributes
        put :update, params: {id: adoption_animal.to_param, adoption_animal: valid_attributes}
        expect(assigns(:adoptionanimal)).to eq(AdoptionAnimal)
      end

      it "redirects to the adoptionanimal" do
        adoptionanimal = AdoptionAnimal.create! valid_attributes
        put :update, params: {id: adoption_animal.to_param, adoption_animal: valid_attributes}
        expect(response).to redirect_to(AdoptionAnimal)
      end
    end

    context "with invalid params" do
      it "assigns the adoptionanimal as @adoptionanimal" do
        adoptionanimal = AdoptionAnimal.create! valid_attributes
        put :update, params: {id: adoption_animal.to_param, adoption_animal: invalid_attributes}
        expect(assigns(:adoptionanimal)).to eq(AdoptionAnimal)
      end

      it "re-renders the 'edit' template" do
        adoptionanimal = AdoptionAnimal.create! valid_attributes
        put :update, params: {id: adoption_animal.to_param, adoption_animal: invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested AdoptionAnimal" do
      adoptionanimal = AdoptionAnimal.create! valid_attributes
      expect {
        delete :destroy, params: {id: AdoptionAnimal.to_param}
      }.to change(Adoptionanimal, :count).by(-1)
    end

    it "redirects to the AdoptionAnimals list" do
      adoptionanimal = AdoptionAnimal.create! valid_attributes
      delete :destroy, params: {id: AdoptionAnimal.to_param}
      expect(response).to redirect_to(AdoptionAnimals_url)
    end
  end

end
